* Main idea
** Gameplay
*** General
    2-player game inspired by Windjammers. There is a single ball and a goal on either side corresponding to each player. The ball starts in the middle and fires off left or right at a random angle acute to the horizontal. Each player has a bat that extends a fixed length from their location, and the player rotates to control where the bat is pointing. There is a goal on the left and right sides of the arena, one for each player. There can be multiple arenas, each with different shapes and sizes for the goals and different obstacles in the middle. The ball will go faster with each regular hit, but the players can push a button for a power hit, or another button to stick the ball to the bat for more control, but it will slow the ball down.
*** Controls
    The left stick controls the player's location, and the right stick controls the angle their bat is at. When the player points in a direction, their character swivels to point the bat at the same direction. There is a quick rotation time, but it doesn't immediately snap to the angle.

* Turning math
** Code

#+BEGIN_SRC gd_script
if get_rot() - target_angle > TURN_THRESHOLD or get_rot() - target_angle < -TURN_THRESHOLD:
	if get_rot() >= 0:
		if target_angle < get_rot() - 3.14159 or target_angle > get_rot(): 
			set_rot(get_rot() + ROT_SPEED * delta)
		else:
			set_rot(get_rot() - ROT_SPEED * delta)
	elif get_rot() < 0:
		if target_angle < get_rot() + 3.14159 and target_angle > get_rot():
			set_rot(get_rot() + ROT_SPEED * delta)
		else:
			set_rot(get_rot() - ROT_SPEED * delta)
#+END_SRC

