* Development progress [2/5]
** DONE Player movement
** TODO Gamepad controls
*** DONE Movement
*** TODO Force adjustment
    1. Full analog
    2. Button mapping
    3. Toggle - single button
** TODO Ball movement (basic)
*** TODO Ball collision
*** TODO Ball gravity
** DONE Make a level
** TODO Make AI

* Main idea
** Gameplay
*** General
    2-player game inspired by Windjammers. There is a single ball and a goal on either side corresponding to each player. The ball starts in the middle and fires off left or right at a random angle acute to the horizontal. Both players have a gravitational force attracting the ball (not each other). The players are able to drop and raise the strength of the gravitational pull (which variable in the gravity equation should be modified? Constant or mass? Probably mass).
*** Controls
    The players will only control the position of their avatars, with a way to adjust their gravitational force. Testing will be done to see how the gravity should be adjusted. Here are some ideas:
    1. Full analog. This will offer the finest control over, but the game will need to be played with controllers that have analog inputs.
    2. Different forces with a button press. The face buttons will have different forces mapped to them, and when the player presses one, the force is adjusted to whatever the button is mapped to. This will offer less control than full analog, but can be played on almost any controller or keyboard.
    3. Single button press to toggle between two predefined force values. This will offer the least control, but if it's fine-tuned enough, it will be extremely simple to pick up and play. It also has the advantage of working with even an Atari controller.

* Input notes
** Axes
   1. Left Stick Horizontal - JOY_AXIS_0
   2. Left Stick Vertical - JOY_AXIS_1
   3. Right Stick Horizontal - JOY_AXIS_2
   4. Right Stick Vertical - JOY_AXIS_3
   5. Joystick Left Trigger - JOY_AXIS_6
   6. Joystick Right Trigger - JOY_AXIS_7
** Functions
   1. Input.get_joy_axis(int device, int axis)
